---

- name: "Development server on Vagrant"
  hosts: "all"
  sudo: "yes"
  remote_user: "vagrant"
  vars:
    admin_user: "vagrant"
  vars_files:
    - "vars/commons.yml"

  roles:
    - { role: common, tags: [common] }
    - { role: aws, tags: [aws] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp }
    - { role: mariadb, tags: [mariadb] }
    - { role: nullmailer, tags: [nullmailer] }
    - { role: php, when: not hhvm, tags: [php] }
    - { role: hhvm, when: hhvm, tags: [hhvm] }
    - { role: php5-xdebug, tags: [xdebug], when: xdebug_install | default(False) }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: dev-tools, tags: [dev-tools] }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup] }
    - { role: wordpress-import, tags: [wordpress, wordpress-import] }
