- name: ntp
  src: resmo.ntp
  version: 0.3.0

- name: logrotate
  src: nickhammond.logrotate
  version: fc3ea4

- name: swapfile
  src: kamaln7.swapfile
  version: 0.4

- name: mailhog
  src: geerlingguy.mailhog
  version: 1.0.3

- name: newrelic-php
  src: chriskite.newrelic-php
  version: c6913d

- name: newrelic-system
  src: sivel.newrelic
  version: 0.1.3
