---
- name: WordPress Server - Install LEMP Stack with PHP 5.6 and MariaDB MySQL
  hosts: web
  sudo: yes

  roles:
    - { role: common, tags: [common] }
    - { role: aws, tags: [aws] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp }
    - { role: users, tags: [users] }
    - { role: sshd, tags: [sshd] }
    - { role: mariadb, tags: [mariadb], when: not mysql_remote_database }
    - { role: nullmailer, tags: [nullmailer mail] }
    - { role: php, when: not hhvm, tags: [php] }
    - { role: hhvm, when: hhvm, tags: [hhvm] }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: newrelic-php, tags: [newrelic] }
    - { role: newrelic-system, tags: [newrelic] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: dev-tools, tags: [dev-tools] }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup] }
