---

- name: "WordPress Import | create wordpress uploads subdirectories"
  file:
    path="{{ www_root }}/{{ item[0] }}/uploads/{{ item[1] }}"
    owner="{{ admin_user }}"
    group="{{ admin_user_group }}"
    state="directory"
    recurse="yes"
  with_nested:
    - "wordpress_sites.keys()"
    - ["blogs.dir", "uploads"]

- name: "WordPress Import | download wordpress uploads"
  become_user: "{{ admin_user }}"
  shell: aws s3 sync {{ wordpress_uploads_s3_dir }}/{{ item[1] }} {{ www_root }}/{{ item[0] }}/uploads/{{ item[1] }} --only-show-errors --delete
  with_nested:
    - "wordpress_sites.keys()"
    - ["blogs.dir", "uploads"]

- include: "scripts.yml"
