---

- name: "WordPress Import | change webroot permissions"
  file:
    path="{{ www_root }}//{{ item.key }}"
    owner="{{ admin_user }}"
    group="{{ admin_user_group }}"
    state="directory"
  with_dict: "{{ wordpress_sites }}"

- name: "WordPress Import | restore logs permissions"
  file:
    path="{{ www_root }}/{{ item.key }}/logs"
    owner="{{ web_user }}"
    group="{{ web_group }}"
    mode="0755"
    state="directory"
  with_dict: "{{ wordpress_sites }}"

- include: "dev.yml"
  when: "'production' not in group_names"

- include: "prod.yml"
  when: "'production' in group_names"

- include: "mysql.yml"
- include: "packages.yml"
