---

- name: "WordPress Import | change webroot permissions"
  file:
    path="{{ www_root }}//{{ item.key }}"
    owner="{{ admin_user }}"
    group="{{ admin_user_group }}"
    state="directory"
  with_dict: "wordpress_sites"

- name: "WordPress Import | restore logs permissions"
  file:
    path="{{ www_root }}/{{ item.key }}/logs"
    owner="{{ web_user }}"
    group="{{ web_group }}"
    mode="0755"
    state="directory"
  with_dict: "wordpress_sites"

- name: "WordPress Import | create wordpress resource directories"
  file:
    path="{{ item }}"
    owner="{{ admin_user }}"
    group="{{ admin_user_group }}"
    state="directory"
  with_items:
    - "{{ private_packages_local_dir }}"
    - "{{ wordpress_config_local_dir }}"

- name: "WordPress Import | create wordpress config subdirectories"
  file:
    path="{{ wordpress_config_local_dir }}/{{ item }}"
    owner="{{ admin_user }}"
    group="{{ admin_user_group }}"
    state="directory"
  with_items: "wordpress_sites.keys()"

- name: "WordPress Import | download private packages"
  sudo: "no"
  shell: aws s3 sync {{ private_packages_s3_dir }} {{ private_packages_local_dir }} --only-show-errors --delete

- name: "WordPress Import | create .env"
  sudo: "no"
  template:
    src="env.j2"
    dest="{{ wordpress_config_local_dir }}/{{ item.key }}/.env"
  with_dict: "wordpress_sites"

- include: "dev.yml"
  when: "'production' not in group_names"

- include: "mysql.yml"
- include: "packages.yml"
