---

- name: "WordPress Import | increase system open files hard limit"
  lineinfile:
    dest="/etc/security/limits.conf"
    state="present"
    regexp="^mysql"
    line="mysql hard nofile 32768"
  when: "not mysql_remote_database"
  tags:
    - "mysql"

- name: "WordPress Import | increase mysql open files limit"
  lineinfile:
    dest="/etc/mysql/my.cnf"
    state="present"
    regexp="^open_files_limit"
    line="open_files_limit = 32768"
    insertafter="^\[mysqld\]"
  when: "not mysql_remote_database"
  notify: "restart mysql"
  tags:
    - "mysql"

- name: "WordPress Import | mysql credentials file"
  sudo: "no"
  template:
    src="user.my.cnf.j2"
    dest="~/.my.cnf"
    mode="0600"
  when: "not mysql_remote_database"
  tags:
    - "mysql"
