---

- name: "WordPress Import | create .env"
  become_user: "{{ admin_user }}"
  template:
    src="env.j2"
    dest="{{ www_root }}/{{ item.key }}/current/.env"
  with_dict: "{{ wordpress_sites }}"
