---

- name: "AWS | create .aws directory"
  file:
    path="/home/{{ admin_user }}/.aws"
    state="directory"
    mode="0700"

- name: "AWS | populate credentials file"
  template:
    src="credentials.j2"
    dest="/home/{{ admin_user }}/.aws/credentials"
    mode="0600"
