---

- name: "AWS | create .aws directory"
  sudo: "no"
  file:
    path="~/.aws"
    state="directory"
    mode="0700"

- name: "AWS | populate credentials file"
  sudo: "no"
  template:
    src="credentials.j2"
    dest="~/.aws/credentials"
    mode="0600"
