---

- include: "aws-credentials.yml"
  become_user: "{{ admin_user }}"
  when: "'aws' not in group_names"

- include: "aws-ec2-user-data.yml"
  when: "'aws' in group_names"

- include: "aws-route53.yml"
  when: "'aws' in group_names"
