---
- name: Ensure sudo group is present
  group: name=sudo state=present

- name: Ensure sudo group has sudo privileges
  lineinfile: dest=/etc/sudoers
              state=present
              regexp="^%sudo"
              line="%sudo ALL=(ALL:ALL) ALL"
              validate="/usr/sbin/visudo -cf %s"

- name: Setup users
  user: name="{{ item.name }}"
        group="{{ item.groups[0] }}"
        groups="{{ item.groups | join(',') }}"
        password="{{ sudoer_passwords[item.name] | default(None) }}"
        state=present
        shell=/bin/bash
        update_password=always
  with_items: users

- name: Add web user sudoers items for services
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ web_user }}-services"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: web_sudoers

- name: Check that supplied local SSH keys exist
  sudo: "no"
  local_action: shell test -f {{ item }} && echo "{{ item }}"
  ignore_errors: yes
  register: existing_ssh_keys
  with_items: "users | map(attribute='keys') | list"

- name: Add SSH keys
  authorized_key: user="{{ item.0.name }}" key="{{ lookup('file', item.1) }}"
  when: "item.1 in existing_ssh_keys.results | map(attribute='stdout') | list"
  with_subelements:
    - users | default([])
    - keys
