---

- name: "Composer | install PHPUnit"
  command: composer global require "phpunit/phpunit=@stable"
    creates="/home/{{ admin_user }}/.config/composer/vendor/bin/phpunit"
  tags:
    - "composer"
    - "phpunit"

- name: "Composer | install PHPCS"
  command: composer global require "squizlabs/php_codesniffer=@stable"
    creates="/home/{{ admin_user }}/.config/composer/vendor/bin/phpcs"
  tags:
    - "composer"
    - "phpcs"

- name: "Composer | install PHPCS WP Coding Standards"
  git:
    repo="https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git"
    dest="/home/{{ admin_user }}/.config/phpcs"
  tags:
    - "composer"
    - "phpcs"

- name: "Composer | add PHPCS WP Coding Standards to PHPCS"
  command: /home/{{ admin_user }}/.config/composer/vendor/bin/phpcs --config-set installed_paths /home/{{ admin_user }}/.config/phpcs
  register: "phpcs_wpcs_result"
  changed_when: "'added successfully' in phpcs_wpcs_result.stdout"
  failed_when: "'successfully' not in phpcs_wpcs_result.stdout"
  tags:
    - "composer"
    - "phpcs"

- name: "Composer | add aliases for PHPCS commands"
  lineinfile:
    dest="/home/{{ admin_user }}/.bashrc"
    line="alias {{ item.name }}='{{ item.command }}'"
    regexp="^alias {{ item.name }}="
    state="present"
    insertafter="EOF"
  with_items:
    - { name: "wpcs", command: "phpcs --standard=WordPress-Core,WordPress-Docs,WordPress-Extra" }
    - { name: "wpcs-core", command: "phpcs --standard=WordPress-Core" }
    - { name: "wpcbf", command: "phpcbf --standard=WordPress-Core,WordPress-Docs,WordPress-Extra" }
    - { name: "wpcbf-core", command: "phpcbf --standard=WordPress-Core" }

- include: "prewarm.yml"
  when: "prewarm_composer_manifest is defined"
