---

- name: "Environment | use google nameserver"
  lineinfile:
    dest="/etc/resolv.conf"
    create="yes"
    state="present"
    line="nameserver 8.8.8.8"
    regexp="^nameserver "
  when: "'vagrant' in group_names"
  tags:
    - "environment"
    - "dns"

- name: "Environment | add github.com to known hosts"
  lineinfile:
    dest="/etc/ssh/ssh_known_hosts"
    create="yes"
    state="present"
    line="github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
    regexp="^github\.com"
  tags:
    - "environment"
    - "known-hosts"

- name: "Environment | set default editor to vim"
  shell: update-alternatives --set editor /usr/bin/vim.basic
  register: "update_editor_result"
  changed_when: "'using /usr/bin/vim.basic' in update_editor_result.stdout"
  tags:
    - "environment"
    - "editor"

- name: "Environment | set useful aliases"
  sudo: "no"
  lineinfile:
    dest="~/.bashrc"
    line="alias {{ item.name }}='{{ item.command }}'"
    regexp="^alias {{ item.name }}="
    state="present"
    insertafter="EOF"
  with_items:
    - { name: "alog", command: "less +G {{ www_root }}/{{ wordpress_sites.keys()[0] }}/logs/access.log" }
    - { name: "dlog", command: "less +G {{ www_root }}/{{ wordpress_sites.keys()[0] }}/logs/debug.log" }
    - { name: "elog", command: "less +G {{ www_root }}/{{ wordpress_sites.keys()[0] }}/logs/error.log" }
