---

# Overrides
default_timezone: "America/New_York"
mailhog_install_ssmtp: no
php_display_errors: "Off"
php_sendmail_path: "/usr/sbin/sendmail -t -i"
sshd_permit_root_login: false
strip_www: false
sudoer_passwordless: true

# In addition to the ENV variables used in `wordpress_sites.yml`, define the
# following variables via host vars or extra vars:
#
# aws_default_region
# aws_access_key_id
# aws_secret_access_key
# aws_route53_zone_id
# composer_github_access_token
# fedora_proxy_url
# mysql_root_password
# mysql_backup_s3_dir
# newrelic_license_key
# wordpress_uploads_s3_dir

# For production hosts, additionally define/override these variables:
#
# mail_smtp_server: "server.example.com:port"
# mail_user
# mail_password
# mysql_remote_database
# php5_newrelic_appname
