---

web_user: "www-data"

users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys: []
  - name: "{{ admin_user }}"
    groups:
      - "adm"
      - "staff"
      - "sudo"
      - "{{ web_group }}"
    keys:
      - "https://github.com/rekmla.keys"
      - "https://github.com/modelm.keys"
      - "https://github.com/Es0teric.keys"
      - "https://github.com/nalonsopress.keys"
        #- "https://github.com/skoranda.keys"
