---

wordpress_sites:
  commons:
    env:
      admin_email: "{{ wordpress_admin_email | default('admin@example.com') }}"
      auth_key: "{{ wordpress_auth_key | default(omit) }}"
      auth_salt: "{{ wordpress_auth_salt | default(omit) }}"
      logged_in_key: "{{ wordpress_logged_in_key | default(omit) }}"
      logged_in_salt: "{{ wordpress_logged_in_salt | default(omit) }}"
      nonce_key: "{{ wordpress_nonce_key | default(omit) }}"
      nonce_salt: "{{ wordpress_nonce_salt | default(omit) }}"
      secure_auth_key: "{{ wordpress_secure_auth_key | default(omit) }}"
      secure_auth_salt: "{{ wordpress_secure_auth_salt | default(omit) }}"
      cbox_auth_api_key: "{{ cbox_auth_api_key | default(omit) }}"
      cbox_auth_api_secret: "{{ cbox_auth_api_secret | default(omit) }}"
      cbox_auth_api_url: "{{ cbox_auth_api_url | default(omit) }}"
      core_humcore_namespace: "{{ core_humcore_namespace | default(omit) }}"
      core_humcore_collection_pid: "{{ core_humcore_collection_pid | default(omit) }}"
      core_humcore_temp_dir: "{{ www_root }}/commons/current/web/app/uploads/humcore"
      core_http_debug: "false"
      core_error_log: "{{ www_root }}/commons/logs/humcore_error.log"
      core_fedora_protocol: "{{ core_fedora_protocol | default(omit) }}"
      core_fedora_host: "{{ core_fedora_host | default(omit) }}"
      core_fedora_port: "{{ core_fedora_port | default(omit) }}"
      core_fedora_path: "{{ core_fedora_path | default(omit) }}"
      core_fedora_login: "{{ core_fedora_login | default(omit) }}"
      core_fedora_password: "{{ core_fedora_password | default(omit) }}"
      core_solr_protocol: "{{ core_solr_protocol | default(omit) }}"
      core_solr_host: "{{ core_solr_host | default(omit) }}"
      core_solr_port: "{{ core_solr_port | default(omit) }}"
      core_solr_path: "{{ core_solr_path | default(omit) }}"
      core_solr_core: "{{ core_solr_core | default(omit) }}"
      core_ezid_protocol: "{{ core_ezid_protocol | default(omit) }}"
      core_ezid_host: "{{ core_ezid_host | default(omit) }}"
      core_ezid_port: "{{ core_ezid_port | default(omit) }}"
      core_ezid_path: "{{ core_ezid_path | default(omit) }}"
      core_ezid_login: "{{ core_ezid_login | default(omit) }}"
      core_ezid_password: "{{ core_ezid_password | default(omit) }}"
      core_ezid_prefix: "{{ core_ezid_prefix | default(omit) }}"
      core_oai_protocol: "{{ core_oai_protocol | default(omit) }}"
      core_oai_host: "{{ core_oai_host | default(omit) }}"
      core_oai_port: "{{ core_oai_port | default(omit) }}"
      core_oai_path: "{{ core_oai_path | default(omit) }}"
      db_host: "{{ wordpress_db_host | default('localhost') }}"
      db_name: "{{ wordpress_db_name | default('wordpress') }}"
      db_user: "{{ wordpress_db_user | default('dbuser') }}"
      global_smtp_from: "{{ wordpress_smtp_from | default(omit) }}"
      wp_env: "{{ ('production' in group_names) | ternary('production', 'development') }}"
      wp_home: "https://commons.mla.org"
      wp_siteurl: "https://commons.mla.org"
      wp_domain: "commons.mla.org"
      wp_logs_dir: "{{ www_root }}/commons/logs"
      wpcom_api_key: "{{ akismet_api_key | default(omit) }}"
    multisite:
      enabled: true
      subdomains: true
      base_path: "/"
    repo: "git@github.com:mlaa/commons.git"
    repo_branch: "master"
    site_hosts:
      - "commons.mla.org"
    site_install: false
    site_title: "MLA Commons"
    ssl:
      enabled: true
